---
version_control: metacpan
src_repo: Config-AutoConf
tag_prefix: "^v"
seperator: "."
last_query:
  time_stamp: 2020-04-26 07:39:52.255554420 +00:00
  raw_data: |
    {
       "version_numified" : 0.318,
       "id" : "NHmCqc46hDOB7Jb_aiDjgL1N8_0",
       "provides" : [
          "Config::AutoConf"
       ],
       "changes_file" : "Changes",
       "status" : "latest",
       "checksum_md5" : "0bea721ad3996e20324b84b3b924ec71",
       "abstract" : "A module to implement some of AutoConf macros in pure perl.",
       "authorized" : true,
       "download_url" : "https://cpan.metacpan.org/authors/id/R/RE/REHSACK/Config-AutoConf-0.318.tar.gz",
       "first" : false,
       "deprecated" : false,
       "author" : "REHSACK",
       "metadata" : {
          "generated_by" : "ExtUtils::MakeMaker version 7.42, CPAN::Meta::Converter version 2.150010",
          "meta-spec" : {
             "url" : "http://search.cpan.org/perldoc?CPAN::Meta::Spec",
             "version" : 2
          },
          "x_serialization_backend" : "JSON::PP version 4.04",
          "prereqs" : {
             "test" : {
                "requires" : {
                   "ExtUtils::CBuilder" : "0.23",
                   "Test::More" : "0.9"
                }
             },
             "configure" : {
                "requires" : {
                   "ExtUtils::MakeMaker" : "0"
                }
             },
             "build" : {
                "requires" : {}
             },
             "runtime" : {
                "recommends" : {
                   "File::Slurper" : "0",
                   "ExtUtils::CBuilder" : "0.280220",
                   "Scalar::Util" : "1.18"
                },
                "requires" : {
                   "File::Spec" : "0",
                   "Carp" : "0",
                   "File::Temp" : "0",
                   "File::Basename" : "0",
                   "Text::ParseWords" : "0",
                   "base" : "0",
                   "warnings" : "0",
                   "Exporter" : "0",
                   "Config" : "0",
                   "strict" : "0",
                   "Capture::Tiny" : "0",
                   "Cwd" : "0"
                }
             },
             "develop" : {
                "requires" : {
                   "Test::PerlTidy" : "0",
                   "Test::Spelling" : "0",
                   "Test::Pod::Spelling::CommonMistakes" : "0",
                   "Test::Pod::Coverage" : "0",
                   "Test::Kwalitee" : "0",
                   "Test::Pod" : "0",
                   "Module::CPANTS::Analyse" : "0.96",
                   "Test::CheckManifest" : "0",
                   "Test::CPAN::Changes" : "0"
                }
             }
          },
          "resources" : {
             "x_IRC" : "irc://irc.perl.org/#toolchain",
             "repository" : {
                "type" : "git",
                "url" : "https://github.com:ambs/Config-AutoConf.git",
                "web" : "https://github.com/ambs/Config-AutoConf"
             },
             "license" : [
                "http://dev.perl.org/licenses/"
             ],
             "homepage" : "https://metacpan.org/release/Config-AutoConf",
             "bugtracker" : {
                "mailto" : "bug-Config-AutoConf@rt.cpan.org",
                "web" : "http://rt.cpan.org/Public/Dist/Display.html?Name=Config-AutoConf"
             },
             "x_MailingList" : "mailto:cpan-workers@perl.org'"
          },
          "license" : [
             "perl_5"
          ],
          "release_status" : "stable",
          "dynamic_config" : 1,
          "author" : [
             "Alberto Simoes <ambs@cpan.org>",
             "Jens Rehsack <rehsack@cpan.org"
          ],
          "version" : "0.318",
          "abstract" : "A module to implement some of AutoConf macros in pure perl.",
          "name" : "Config-AutoConf",
          "no_index" : {
             "directory" : [
                "t",
                "inc",
                "t",
                "xt",
                "inc",
                "local",
                "perl5",
                "fatlib",
                "example",
                "blib",
                "examples",
                "eg"
             ]
          }
       },
       "checksum_sha256" : "33c930feec3003de251ca222abe8bbeb74610ad07f65fc16f27d74d195eeab34",
       "date" : "2020-01-02T16:37:25",
       "license" : [
          "perl_5"
       ],
       "archive" : "Config-AutoConf-0.318.tar.gz",
       "distribution" : "Config-AutoConf",
       "resources" : {
          "repository" : {
             "type" : "git",
             "url" : "https://github.com:ambs/Config-AutoConf.git",
             "web" : "https://github.com/ambs/Config-AutoConf"
          },
          "license" : [
             "http://dev.perl.org/licenses/"
          ],
          "homepage" : "https://metacpan.org/release/Config-AutoConf",
          "bugtracker" : {
             "mailto" : "bug-Config-AutoConf@rt.cpan.org",
             "web" : "http://rt.cpan.org/Public/Dist/Display.html?Name=Config-AutoConf"
          }
       },
       "main_module" : "Config::AutoConf",
       "maturity" : "released",
       "stat" : {
          "mtime" : 1577983045,
          "size" : 51016,
          "mode" : 33188
       },
       "name" : "Config-AutoConf-0.318",
       "tests" : {
          "unknown" : 2,
          "pass" : 1319,
          "na" : 1,
          "fail" : 29
       },
       "version" : "0.318",
       "dependency" : [
          {
             "version" : "0.23",
             "phase" : "test",
             "module" : "ExtUtils::CBuilder",
             "relationship" : "requires"
          },
          {
             "module" : "Test::More",
             "version" : "0.9",
             "phase" : "test",
             "relationship" : "requires"
          },
          {
             "module" : "ExtUtils::MakeMaker",
             "version" : "0",
             "phase" : "configure",
             "relationship" : "requires"
          },
          {
             "relationship" : "requires",
             "version" : "0",
             "module" : "Config",
             "phase" : "runtime"
          },
          {
             "phase" : "runtime",
             "version" : "0",
             "module" : "File::Temp",
             "relationship" : "requires"
          },
          {
             "relationship" : "requires",
             "module" : "Capture::Tiny",
             "phase" : "runtime",
             "version" : "0"
          },
          {
             "relationship" : "requires",
             "module" : "strict",
             "version" : "0",
             "phase" : "runtime"
          },
          {
             "module" : "Text::ParseWords",
             "phase" : "runtime",
             "version" : "0",
             "relationship" : "requires"
          },
          {
             "module" : "base",
             "version" : "0",
             "phase" : "runtime",
             "relationship" : "requires"
          },
          {
             "relationship" : "requires",
             "phase" : "runtime",
             "module" : "Carp",
             "version" : "0"
          },
          {
             "module" : "Exporter",
             "version" : "0",
             "phase" : "runtime",
             "relationship" : "requires"
          },
          {
             "relationship" : "requires",
             "version" : "0",
             "phase" : "runtime",
             "module" : "warnings"
          },
          {
             "relationship" : "requires",
             "phase" : "runtime",
             "module" : "File::Spec",
             "version" : "0"
          },
          {
             "phase" : "runtime",
             "version" : "0",
             "module" : "Cwd",
             "relationship" : "requires"
          },
          {
             "module" : "File::Basename",
             "phase" : "runtime",
             "version" : "0",
             "relationship" : "requires"
          },
          {
             "version" : "0.280220",
             "phase" : "runtime",
             "module" : "ExtUtils::CBuilder",
             "relationship" : "recommends"
          },
          {
             "module" : "File::Slurper",
             "phase" : "runtime",
             "version" : "0",
             "relationship" : "recommends"
          },
          {
             "relationship" : "recommends",
             "version" : "1.18",
             "module" : "Scalar::Util",
             "phase" : "runtime"
          },
          {
             "version" : "0.96",
             "module" : "Module::CPANTS::Analyse",
             "phase" : "develop",
             "relationship" : "requires"
          },
          {
             "relationship" : "requires",
             "module" : "Test::CheckManifest",
             "version" : "0",
             "phase" : "develop"
          },
          {
             "relationship" : "requires",
             "version" : "0",
             "phase" : "develop",
             "module" : "Test::Kwalitee"
          },
          {
             "relationship" : "requires",
             "module" : "Test::Pod::Coverage",
             "phase" : "develop",
             "version" : "0"
          },
          {
             "relationship" : "requires",
             "version" : "0",
             "phase" : "develop",
             "module" : "Test::CPAN::Changes"
          },
          {
             "relationship" : "requires",
             "phase" : "develop",
             "version" : "0",
             "module" : "Test::Pod::Spelling::CommonMistakes"
          },
          {
             "relationship" : "requires",
             "module" : "Test::Pod",
             "version" : "0",
             "phase" : "develop"
          },
          {
             "phase" : "develop",
             "module" : "Test::PerlTidy",
             "version" : "0",
             "relationship" : "requires"
          },
          {
             "relationship" : "requires",
             "version" : "0",
             "module" : "Test::Spelling",
             "phase" : "develop"
          }
       ]
    }
